baseURL = 'https://monte.blue/'
languageCode = 'en-us'
title = 'Eduardo Martínez Martínez'
theme = 'hugo-theme-nostyleplease'
hasCJKLanguage = true

[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 2
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
favicon = "favicon.ico"
  [params.theme_config]
    appearance = "auto"
    back_home_text = "index"
    date_format = "02 January 2006"
    isListGroupByDate = false
    main_title = '🏔 ️monte.blue'
